routes/web.php
<?php

use App\Http\Controllers\AddFormController;
use App\Http\Controllers\UserController;
use App\Models\File;
use App\Models\KodeNaskah;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('pages.landing');
});

Route::namespace('Auth')->controller(AuthController::class)->group(function() {
    Route::group(['middleware' => ['guest']], function() {
        Route::get('/login', 'login')->name('login');
        // Route::get('/login', function () {
        //     return redirect('/');
        // })->name('login');
        Route::get('/register', 'register')->name('register');
        Route::post('/store', 'store')->name('store');
        Route::post('/authenticate', 'doLogin')->name('authenticate');
    });
    Route::group(['middleware' => ['auth']], function() {
        // Route::get('/beranda', 'beranda')->name('beranda');
        Route::get('/profile', 'profile')->name('profile');
        Route::post('/logout', 'logout')->name('logout');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('/beranda', 'BerandaController@cekLogin')->name('beranda');
    Route::resource('/berkas-pegawai', BerkasPegawaiController::class);
    Route::resource('/box', BoxController::class);
    Route::resource('/dokumen', DocumentController::class);
    Route::resource('/ekstensi', ExtensionController::class);
    Route::resource('/file', FileController::class);
    Route::resource('/folder', FolderController::class);
    Route::resource('/folder-storage', FolderStorageController::class);
    Route::resource('/kategori-berkas', KategoriBerkasController::class);
    Route::resource('/kode-naskah', KodeNaskahController::class);
    Route::resource('/jurusan', JurusanController::class);
    Route::resource('/kode-unit', KodeUnitController::class);
    Route::resource('/master-agama', MasterAgamaController::class);
    Route::resource('/pegawai', PegawaiController::class);
    Route::resource('/prodi', ProdiController::class);
    Route::resource('/sk', SKController::class);
    Route::resource('/surat-keluar', SuratKeluarController::class);
    Route::resource('/surat-masuk', SuratMasukController::class);
    // ! SUPERADMIN
    Route::resource('/pengguna', UserController::class)->withTrashed();
    Route::put('/update-profile', [UserController::class, 'updateProfile'])->name('update-profile');

    Route::resource('/izin', PermissionController::class);
    Route::resource('/hak-akses', RoleController::class);

    // ! Route Tambahan
    Route::controller(AddFormController::class)->group(function() {
        Route::get('/add-form/select/{model}/{value}/{multiple}', 'select')->name('add-form.select');
    });
    // ! Akun Untuk E-Rapat
    Route::get('/e-rapat', 'PegawaiController@eRapat')->name('export.erapat');
    Route::get('/file-folder', 'FileController@folderView')->name('file.folderView');


    Route::get('/box/label/{id}/{tipeLabel?}', 'BoxController@printLabel')->name('box.label');
    Route::get('/cari-file/{kataKunci?}/{idUnitKerja?}/{idFolder?}', 'FileController@cari')->name('file.cari');
    Route::get('/cari-file-pegawai/{kataKunci?}/{idFolder?}/{idPegawai?}', 'FileController@cariByPegawai')->name('file.cariByPegawai');
    // ! Folder
    Route::get('/file/detail/{idSecret}/{tipeDokumen}', 'FileController@detail')->name('file.detail');
    Route::get('/kembali/{idSecret}/{idUnitKerja?}', 'FileController@kembali')->name('file.kembali');
    Route::get('/unit-folder', 'FileController@unitfolder')->name('file.unitfolder');
    Route::get('/folders/{idSecret}/{idUnitKerja?}', 'FileController@folder')->name('file.folder');
    Route::get('/folder-pegawais/{parentFolderPegawai}/{idPegawai}/{idUnitKerja?}', 'FileController@folderPegawai')->name('file.folderPegawai');
    Route::get('/data-pegawai/{idSecret}/{idPegawai}', 'FileController@dataPegawai')->name('file.dataPegawai');
});

Route::controller(PencarianController::class)->group(function() {
    Route::get('/cari-berkas/{boxId}', 'byBox')->name('cari-berkas.qrcode');
    Route::get('/lihat-file-direct/{id}/{tipeFile}', 'viewFile')->name('lihat-file');
    Route::get('/download-file-direct/{id}/{tipeFile}', 'downloadFile')->name('unduh-file');
    Route::get('/lihat-file/{unique_id}/{id}/{tipeFile}/{password}', 'viewFileBox')->name('lihat-file-box');
    Route::get('/download-file/{unique_id}/{id}/{tipeFile}/{password}', 'downloadFileBox')->name('unduh-file-box');

});

Route::get('test-function', function () {
    
});

Route::get('/cari', function () {
    return view('pages.cari');
});

app/View/Components/Pages/Dokumen/Create.php
<?php

namespace App\View\Components\Pages\Dokumen;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Create extends Component
{
    public $jenisAkses, $unitKerjas, $pegawais, $boxes, $folders, $selected, $accepts, $creators;
    /**
     * Create a new component instance.
     */
    public function __construct(
        $jenisAkses = false,
        $unitKerjas = false,
        $pegawais   = false,
        $boxes      = false,
        $folders    = false,
        $selected   = false,
        $accepts    = false,
        $creators   = false,
    )
    {
        $this->jenisAkses   = $jenisAkses;
        $this->unitKerjas   = $unitKerjas;
        $this->pegawais     = $pegawais;
        $this->boxes        = $boxes;
        $this->folders      = $folders;
        $this->selected     = $selected;
        $this->accepts      = $accepts;
        $this->creators     = $creators;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.'.config('variables.templateName').'.pages.dokumen.create');
    }
}

app/View/Components/Pages/Dokumen/Detail.php
<?php

namespace App\View\Components\Pages\Dokumen;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Detail extends Component
{
    public $dataDokumen;
    /**
     * Create a new component instance.
     */
    public function __construct(
        $dataDokumen = false,
    )
    {
        $this->dataDokumen = $dataDokumen;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.'.config('variables.templateName').'.pages.dokumen.detail');
    }
}

app/View/Components/Pages/Dokumen/Edit.php
<?php

namespace App\View\Components\Pages\Dokumen;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Edit extends Component
{
    public $dataDokumen, $jenisAkses, $unitKerjas, $pegawais, $boxes, $folders, $selectJenisAkses, $selectBox, $selectFolder, $accepts, $creators, $selectCreator;
    /**
     * Create a new component instance.
     */
    public function __construct(
        $dataDokumen,
        $jenisAkses         = false,
        $unitKerjas         = false,
        $pegawais           = false,
        $boxes              = false,
        $folders            = false,
        $selectJenisAkses   = false,
        $selectBox          = false,
        $selectFolder       = false,
        $accepts            = false,
        $creators           = false,
        $selectCreator      = false,
    )
    {
        $this->dataDokumen      = $dataDokumen;
        $this->jenisAkses       = $jenisAkses;
        $this->unitKerjas       = $unitKerjas;
        $this->pegawais         = $pegawais;
        $this->boxes            = $boxes;
        $this->folders          = $folders;
        $this->selectJenisAkses = $selectJenisAkses;
        $this->selectBox        = $selectBox;
        $this->selectFolder     = $selectFolder;
        $this->accepts          = $accepts;
        $this->creators         = $creators;
        $this->selectCreator    = $selectCreator;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.'.config('variables.templateName').'.pages.dokumen.edit');
    }
}

app/View/Components/Pages/Dokumen/Index.php
<?php

namespace App\View\Components\Pages\Dokumen;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Index extends Component
{
    public $datas;
    /**
     * Create a new component instance.
     */
    public function __construct(
        $datas = false,
    )
    {
        $this->datas = $datas;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.'.config('variables.templateName').'.pages.dokumen.index');
    }
}

resources/views/pages/scoxe/dokumen/create.blade.php
@extends('layouts.'.env('TEMPLATE').'.app')

@section('content')

<x-layouts.page-form title="Dokumen" menu="Dokumen" submenu="Tambah" formLabel="Tambah Dokumen" :urlback="route('dokumen.index')">

    <x-forms.form :action="route('dokumen.store')" method="POST" id="form" enctype="multipart/form-data">
                
        <x-forms.textarea label="Nama" class="text-uppercase" name="nama" :value="old('nama')" required></x-forms.textarea>
                
        <x-forms.selectbox label="Jenis Akses File" name="jenis_akses_id" required :datas="$jenisAkses" :selected="old('jenis_akses_id')" ></x-forms.selectbox>

        <div id="tim">
            <x-forms.selectbox label="Tim" name="role_id[]" :datas="$roles" :selected="old('role_id') ?? $selected" hasMultiple="true"></x-forms.selectbox>
        </div>

        <div id="tag">
            <x-forms.selectbox label="Tag Perorang" name="pegawai_id[]" :datas="$pegawais" :selected="old('pegawai_id')" hasMultiple="true"></x-forms.selectbox>
        </div>

        <x-forms.selectbox label="Box/Gobi" name="box_id[]" :datas="$boxes" :selected="old('box_id')" hasMultiple="true"></x-forms.selectbox>

        <x-forms.file label="File" name="attachment" required  :accept="$accepts"></x-forms.fi>

        <x-button type="submit" class="btn-success w-100" id="" label="Simpan"/>
        
    </x-forms.form>

</x-layouts.page-form>

@endsection

@push('js')
    <script>
        $( document ).ready(function() {
            $("#tim, #tag").hide();

            $("select[name='jenis_akses_id']").on('click change keyup keydown', function () { 
                var id = $(this).val();
                switch (id) {
                    case '3':
                        $("#tag").show();
                        $("#tim").hide();
                        break;
                        
                    case '4':
                        $("#tim").show();
                        $("#tag").hide();
                        break;
                
                    default:
                        $("#tim, #tag").hide();
                        break;
                }
            })
        });
    </script>
@endpush

resources/views/pages/scoxe/dokumen/detail.blade.php
<div class="row">
    <div class="card mb-3 col-12">
        <div class="card-header text-white bg-warning text-uppercase">Informasi Dokumen</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered mt-1">
                    <tr>
                        <td>Nama Dokumen</td>
                        <td>{{ $data->nama }}</td>
                    </tr>
                    @if ($data->file->boxes)
                        @php
                            $nama = $nomor = $bagian = $lokasi = ''; 
                            foreach ($data->file->boxes as $key => $item) {
                                $nama .= ($key > 0 ? ',' : '' ) . $item->namaTahun;
                                $nomor .= ($key > 0 ? ',' : '' ) . $item->nomor;
                                $bagian .= ($key > 0 ? ',' : '' ) . $item->bagian;
                                $lokasi .= ($key > 0 ? ',' : '' ) . $item->lokasi;
                            }
                        @endphp
                    @endif
                    <tr>
                        <td>Nama Box/Kotak</td>
                        <td>
                            {{ $nama ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <td>Nomor</td>
                        <td>
                            {{ $nomor ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <td>Kepemilikan</td>
                        <td>
                            {{ $bagian ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <td>Lokasi</td>
                        <td>{{ $lokasi ?? '' }}</td>
                    </tr>
                    <tr>
                        <td>Operator</td>
                        <td>{{ $data->creator->name }}</td>
                    </tr>
                    <tr>
                        <td>Download</td>
                        <td>
                            <x-ahref :link="route('unduh-file', ['id'=> $data->idSecret, 'tipeFile' => 'dokumen'])" target="_blank" class="btn btn-info" text="Download"></x-ahref>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

resources/views/pages/scoxe/dokumen/edit.blade.php
@extends('layouts.'.env('TEMPLATE').'.app')

@section('content')

<x-layouts.page-form title="Dokumen" menu="Dokumen" submenu="Ubah" formLabel="Ubah Dokumen" :urlback="route('dokumen.index')">

    <x-forms.form :action="route('dokumen.update', $data->id_secret)" method="POST" id="form" :urlback="route('dokumen.index')" enctype="multipart/form-data">

        @method('PUT')
        <input type="hidden" name="id" value="{{ $data->id_secret }}" required>

        <x-forms.text label="Nama" class="text-uppercase" name="nama" :value="old('nama') ?? $data->nama" threshold="200" required></x-forms.text>
                
        <x-forms.selectbox label="Jenis Akses File" name="jenis_akses_id" required :datas="$jenisAkses" :selected="old('jenis_akses_id') ?? $data->file->jenis_akses_id" ></x-forms.selectbox>

        <div id="tim">
            <x-forms.selectbox label="Tim" name="role_id[]" :datas="$roles" :selected="old('role_id') ?? ($data->file->jenis_akses_id == 4 ? $selectJenisAkses : NULL)" hasMultiple="true"></x-forms.selectbox>
        </div>

        <div id="tag">
            <x-forms.selectbox label="Tag Perorang" name="pegawai_id[]" :datas="$pegawais" :selected="old('pegawai_id') ?? ($data->file->jenis_akses_id == 3 ? $selectJenisAkses : NULL)" hasMultiple="true"></x-forms.selectbox>
        </div>

        <x-forms.selectbox label="Box/Gobi" name="box_id[]" :datas="$boxes" :selected="old('box_id') ?? $selectBox" hasMultiple="true"></x-forms.selectbox>

        <x-forms.file label="File" name="attachment" :accept="$accepts"></x-forms.file>

        <x-button type="submit" class="btn-success w-100" id="" label="Simpan"/>
        
    </x-forms.form>

</x-layouts.page-form>

@endsection

@push('js')
    <script>
        $( document ).ready(function() {
            $("#tim, #tag").hide();
            var jenisAksesId = "{{ (old('jenis_akses_id') ?? $data->file->jenis_akses_id) }}";
            showHide(jenisAksesId);
            $("select[name='jenis_akses_id']").on('click, change', function () { 
                var id = $(this).val();
                showHide(id);
            })

            function showHide(id)
            {
                switch (id) {
                    case '3':
                        $("#tag").show();
                        $("#tim").hide();
                        break;
                        
                    case '4':
                        $("#tim").show();
                        $("#tag").hide();
                        break;
                
                    default:
                        $("#tim, #tag").hide();
                        break;
                }
            }
        });
    </script>
@endpush

resources/views/pages/scoxe/dokumen/index.blade.php
@extends('layouts.'.env('TEMPLATE').'.app')

@section('content')

<x-layouts.page-index-table title="Dokumen" menu="Dokumen" :route="route('dokumen.create')" buttonTambah="Tambah Dokumen">

    <div class="table-responsive mt-4">
        <table id="datatable-buttons" class="table table-striped dt-responsive nowrap">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Nama Berkas</th>
                    <th>Lihat</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($documents as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $item->nama }}</td>
                        <td>
                            <x-ahref :link="route('lihat-file', ['id'=> $item->idSecret, 'tipeFile' => 'dokumen'])" target="_blank" class="btn btn-sm btn-primary" text="Lihat"></x-ahref>
                        </td>
                        <td>
                            <x-tables.button-action route="dokumen" :id="$item->idSecret" :labelDelete="$item->nomor"></x-tables.button-action>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

</x-layouts.page-index-table>

@endsection