routes/web.php
<?php

use App\Http\Controllers\AddFormController;
use App\Http\Controllers\UserController;
use App\Models\File;
use App\Models\KodeNaskah;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('pages.landing');
});

Route::namespace('Auth')->controller(AuthController::class)->group(function() {
    Route::group(['middleware' => ['guest']], function() {
        Route::get('/login', 'login')->name('login');
        // Route::get('/login', function () {
        //     return redirect('/');
        // })->name('login');
        Route::get('/register', 'register')->name('register');
        Route::post('/store', 'store')->name('store');
        Route::post('/authenticate', 'doLogin')->name('authenticate');
    });
    Route::group(['middleware' => ['auth']], function() {
        // Route::get('/beranda', 'beranda')->name('beranda');
        Route::get('/profile', 'profile')->name('profile');
        Route::post('/logout', 'logout')->name('logout');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('/beranda', 'BerandaController@cekLogin')->name('beranda');
    Route::resource('/berkas-pegawai', BerkasPegawaiController::class);
    Route::resource('/box', BoxController::class);
    Route::resource('/dokumen', DocumentController::class);
    Route::resource('/ekstensi', ExtensionController::class);
    Route::resource('/file', FileController::class);
    Route::resource('/folder', FolderController::class);
    Route::resource('/folder-storage', FolderStorageController::class);
    Route::resource('/kategori-berkas', KategoriBerkasController::class);
    Route::resource('/kode-naskah', KodeNaskahController::class);
    Route::resource('/jurusan', JurusanController::class);
    Route::resource('/kode-unit', KodeUnitController::class);
    Route::resource('/master-agama', MasterAgamaController::class);
    Route::resource('/pegawai', PegawaiController::class);
    Route::resource('/prodi', ProdiController::class);
    Route::resource('/sk', SKController::class);
    Route::resource('/surat-keluar', SuratKeluarController::class);
    Route::resource('/surat-masuk', SuratMasukController::class);
    // ! SUPERADMIN
    Route::resource('/pengguna', UserController::class)->withTrashed();
    Route::put('/update-profile', [UserController::class, 'updateProfile'])->name('update-profile');

    Route::resource('/izin', PermissionController::class);
    Route::resource('/hak-akses', RoleController::class);

    // ! Route Tambahan
    Route::controller(AddFormController::class)->group(function() {
        Route::get('/add-form/select/{model}/{value}/{multiple}', 'select')->name('add-form.select');
    });
    // ! Akun Untuk E-Rapat
    Route::get('/e-rapat', 'PegawaiController@eRapat')->name('export.erapat');
    Route::get('/file-folder', 'FileController@folderView')->name('file.folderView');


    Route::get('/box/label/{id}/{tipeLabel?}', 'BoxController@printLabel')->name('box.label');
    Route::get('/cari-file/{kataKunci?}/{idUnitKerja?}/{idFolder?}', 'FileController@cari')->name('file.cari');
    Route::get('/cari-file-pegawai/{kataKunci?}/{idFolder?}/{idPegawai?}', 'FileController@cariByPegawai')->name('file.cariByPegawai');
    // ! Folder
    Route::get('/file/detail/{idSecret}/{tipeDokumen}', 'FileController@detail')->name('file.detail');
    Route::get('/kembali/{idSecret}/{idUnitKerja?}', 'FileController@kembali')->name('file.kembali');
    Route::get('/unit-folder', 'FileController@unitfolder')->name('file.unitfolder');
    Route::get('/folders/{idSecret}/{idUnitKerja?}', 'FileController@folder')->name('file.folder');
    Route::get('/folder-pegawais/{parentFolderPegawai}/{idPegawai}/{idUnitKerja?}', 'FileController@folderPegawai')->name('file.folderPegawai');
    Route::get('/data-pegawai/{idSecret}/{idPegawai}', 'FileController@dataPegawai')->name('file.dataPegawai');
});

Route::controller(PencarianController::class)->group(function() {
    Route::get('/cari-berkas/{boxId}', 'byBox')->name('cari-berkas.qrcode');
    Route::get('/lihat-file-direct/{id}/{tipeFile}', 'viewFile')->name('lihat-file');
    Route::get('/download-file-direct/{id}/{tipeFile}', 'downloadFile')->name('unduh-file');
    Route::get('/lihat-file/{unique_id}/{id}/{tipeFile}/{password}', 'viewFileBox')->name('lihat-file-box');
    Route::get('/download-file/{unique_id}/{id}/{tipeFile}/{password}', 'downloadFileBox')->name('unduh-file-box');

});

Route::get('test-function', function () {
    
});

Route::get('/cari', function () {
    return view('pages.cari');
});

app/Models/KodeNaskah.php
<?php

namespace App\Models;

use App\Models\Scopes\RoleKodeNaskahScope;
use App\Traits\Mutators\EncryptId;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class KodeNaskah extends Model
{
    use HasFactory, EncryptId;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'kode_naskahs';

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope(new RoleKodeNaskahScope);
        // Order by kode ASC
        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('kode', 'asc');
        });
    }
    
    // ! RELATIONS
    /**
     * Get the Creator that owns the Kode Naskah
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by', 'id');
    }

    /**
     * Get all of the Surat Keluar for the Kode Naskah
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function suratKeluars(): HasMany
    {
        return $this->hasMany(SuratKeluar::class, 'kode_naskah_id', 'id');
    }
    
    /**
     * Get all of the SK for the Kode Naskah
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sks(): HasMany
    {
        return $this->hasMany(SK::class, 'kode_naskah_id', 'id');
    }
    // ! END RELATIONS
    
    // ! ACCESSORS & MUTATORS
    protected function idSecret(): Attribute
    {
        return new Attribute(
            get: fn () => $this->encrypt($this->id),
        );
    }

    protected function kode(): Attribute
    {
        return new Attribute(
            set: fn (string $value) => Str::upper($value),
        );
    }
    // ! END ACCESSORS & MUTATORS

    // ! SCOPE
    protected function scopeView($query)
    {
        return $query->get(['id', 'kode', 'substansi'])->map(function($data) {
            $data['key']    = $data->idSecret;
            $data['text']   = $data->kode . ' - ' . $data->substansi;

            return $data;
        });
    }
    // ! END SCOPE
}

app/Http/Controllers/KodeNaskahController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreKodeNaskahRequest;
use App\Http\Requests\UpdateKodeNaskahRequest;
use App\Models\KodeNaskah;
use App\Services\KodeNaskah\KodeNaskahServiceInterface;
use App\Traits\Accessors\DecryptId;
use App\Traits\Response as TraitsResponse;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Illuminate\View\View;
use Spatie\Permission\Models\Role;


class KodeNaskahController extends Controller
{
    use TraitsResponse, DecryptId;

    public $routeIndex  = 'kode-naskah.index';
    public $folder;
    public $title       = 'Kode Naskah';

    public function __construct(
        protected KodeNaskahServiceInterface $kodeNaskahService
    ) {
        $this->middleware('auth');
        $this->folder = 'pages.'.config('variables.templateName').'.kode-naskah';
    }

    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        abort_if(Gate::denies('kodenaskah-index'), Response::HTTP_FORBIDDEN);
        
        return view($this->folder.'.index', [
            'kodeNaskahs'  => $this->kodeNaskahService->allWithOrder('id', 'asc'),
            'title' => $this->title,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        abort_if(Gate::denies('kodenaskah-create'), Response::HTTP_FORBIDDEN);

        return view($this->folder.'.create', [
            'title' => $this->title,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreKodeNaskahRequest $request): RedirectResponse
    {
        abort_if(Gate::denies('kodenaskah-create'), Response::HTTP_FORBIDDEN);
        
        try {
            $saving = $this->kodeNaskahService->store($request->validated());
            if (!$saving instanceof KodeNaskah) {
                throw new Exception($saving);
            }
            return redirect()->route($this->routeIndex)->with([
                'data'      => $saving,
                'status'    => true,
                'message'   => $this->pesanFlash(200),
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->with([
                'status'    => false,
                'message'   => $this->pesanFlash(),
            ]);            
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(KodeNaskah $kSK)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $kodeNaskahId): View
    {
        abort_if(Gate::denies('kodenaskah-update'), Response::HTTP_FORBIDDEN);
        
        return view($this->folder.'.edit', [
            'data'  => $this->kodeNaskahService->findById($this->decrypt($kodeNaskahId)),
            'title' => $this->title,
        ]);

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateKodeNaskahRequest $request, string $kodeNaskahId): RedirectResponse
    {
        abort_if(Gate::denies('kodenaskah-update'), Response::HTTP_FORBIDDEN);
        
        $kodeNaskahData = array_filter($request->validated(), fn ($value) => !is_null($value));
        try {
            $saving = $this->kodeNaskahService->update($request->id, $kodeNaskahData);
            if (!$saving) {
                throw new Exception($saving);
            }
            return redirect()->route($this->routeIndex)->with([
                'data'      => $saving,
                'status'    => true,
                'message'   => $this->pesanFlash(201),
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->with([
                'status'    => false,
                'message'   => $this->pesanFlash(),
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $kodeNaskahId): RedirectResponse
    {
        abort_if(Gate::denies('kodenaskah-delete'), Response::HTTP_FORBIDDEN);

        try {
            $saving = $this->kodeNaskahService->delete($this->decrypt($kodeNaskahId));
            if (!$saving) {
                throw new Exception($saving);
            }
            return redirect()->route($this->routeIndex)->with([
                'data'      => $saving,
                'status'    => true,
                'message'   => $this->pesanFlash(202),
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->with([
                'status'    => false,
                'message'   => $this->pesanFlash(),
            ]);
        }
    }
}

app/View/Components/Pages/KodeNaskah/Create.php
<?php

namespace App\View\Components\Pages\KodeNaskah;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Create extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        // 
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.'.config('variables.templateName').'.pages.kode-naskah.create');
    }
}

app/View/Components/Pages/KodeNaskah/Edit.php
<?php

namespace App\View\Components\Pages\KodeNaskah;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Edit extends Component
{
    public $dataKodeNaskah;
    /**
     * Create a new component instance.
     */
    public function __construct(
        $dataKodeNaskah,
    )
    {
        $this->dataKodeNaskah      = $dataKodeNaskah;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.'.config('variables.templateName').'.pages.kode-naskah.edit');
    }
}

app/View/Components/Pages/KodeNaskah/Index.php
<?php

namespace App\View\Components\Pages\KodeNaskah;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Index extends Component
{
    public $datas;
    /**
     * Create a new component instance.
     */
    public function __construct(
        $datas = false,
    )
    {
        $this->datas = $datas;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.'.config('variables.templateName').'.pages.kode-naskah.index');
    }
}

resources/views/pages/scoxe/kode-naskah/create.blade.php
@extends('layouts.'.env('TEMPLATE').'.app')

@section('content')

<x-layouts.page-form title="Kode Naskah" menu="Kode Naskah" submenu="Tambah" formLabel="Tambah Kode Naskah" :urlback="route('kode-naskah.index')">

    <x-forms.form :action="route('kode-naskah.store')" method="POST" id="form">
        
        <x-forms.textarea label="Substansi" name="substansi" :value="old('substansi')" rows="5" required autofocus></x-forms.textarea>
        
        <x-forms.text label="Kode" class="text-uppercase" name="kode" :value="old('kode')" threshold="10" required></x-forms.text>

        <x-forms.textarea label="Deskripsi" name="deskripsi" :value="old('deskripsi')" rows="5"></x-forms.textarea>
                
        <x-button type="submit" class="btn-success w-100" id="" label="Simpan"/>
        
    </x-forms.form>

</x-layouts.page-form>

@endsection

resources/views/pages/scoxe/kode-naskah/edit.blade.php
@extends('layouts.'.env('TEMPLATE').'.app')

@section('content')

<x-layouts.page-form title="Kode Naskah" menu="Kode Naskah" submenu="Ubah" formLabel="Ubah Kode Naskah" :urlback="route('kode-naskah.index')">

    <x-forms.form :action="route('kode-naskah.update', $data->id_secret)" method="POST" id="form" :urlback="route('kode-naskah.index')">

        @method('PUT')
        <input type="hidden" name="id" value="{{ $data->id_secret }}" required>
        
        <x-forms.textarea label="Substansi" name="substansi" :value="old('substansi') ?? $data->substansi" rows="5" required autofocus></x-forms.textarea>
        
        <x-forms.text label="Kode" class="text-uppercase" name="kode" :value="old('kode') ?? $data->kode" threshold="10" required></x-forms.text>
        
        <x-forms.textarea label="Deskripsi" name="deskripsi" :value="old('deskripsi') ?? $data->deskripsi" rows="5"></x-forms.textarea>
                
        <x-button type="submit" class="btn-success w-100" id="" label="Simpan"/>
        
    </x-forms.form>

</x-layouts.page-form>

@endsection

resources/views/pages/scoxe/kode-naskah/index.blade.php
@extends('layouts.'.env('TEMPLATE').'.app')

@section('content')

<x-layouts.page-index-table title="Master Kode Naskah" menu="Kode Naskah" :route="route('kode-naskah.create')" buttonTambah="Tambah Kode Naskah">

    <div class="table-responsive mt-4">
        <table id="datatable-buttons" class="table table-bordered table-striped dt-responsive text-center">
            <thead class="thead-light">
                <tr>
                    <th width="5%">No.</th>
                    @canany(['update-kodenaskah', 'delete-kodenaskah'])
                    <th width="5%">#</th>
                    @endcan
                    <th width="10%">Kode</th>
                    <th width="50%">Substansi</th>
                    <th>Deskripsi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($kodeNaskahs as $key =>$item)
                    <tr>
                        <td width="5%">{{ ($key+1) }}</td>
                        @canany(['update-kodenaskah', 'delete-kodenaskah'])
                        <td width="5%">
                                <x-tables.button-action route="kode-naskah" :id="$item->idSecret" :labelDelete="$item->substansi"></x-tables.button-action>
                            </td>
                        @endcan
                        <td width="10%">{{ $item->kode }}</td>
                        <td width="50%">{{ $item->substansi }}</td>
                        <td>{{ $item->deskripsi }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

</x-layouts.page-index-table>

@endsection